### ISSUE TITLE
Database of creature name -> battle sprite

### ISSUE THREAD

**Issue by gurgalex** [berated-bert/siralim-planner#1]
rovermicrover has compiled a mapping of the creature names with their respective battle sprite images internally.
https://github.com/rovermicrover/siralim-ultimate-api/blob/main/app/data/creatures.csv

The fields **name**, and **battle_sprite** will be of interest.

**Comment by berated-bert** [comment]
This is fantastic, thanks - I didn't know such a dataset (nor an API for SU) existed. I'll see if I can work on adding the creature sprites in.

**Comment by berated-bert** [comment]
Thanks again, I have added creature sprites.
