### ISSUE TITLE
Reset Button clears /siralim-planner/ from path

### ISSUE THREAD

**Issue by aauukerochan** [berated-bert/siralim-planner#18]
Hi 👋 
Thanks for maintaining Siralim Planner!
I'm pretty new to Siralim, and being able to see visual versions of builds people recommend has been a godsend.

Someone mentioned this in the Siralim discord and I thought I'd file an issue on their behalf.

### Description:

Clicking on the Reset Button clears out `/siralim-planner/` from the path.
This causes any future pushes to the router history to be from the base host, so exports fail.

### Environment:
Any browser

### Steps to Reproduce:

1. Visit https://berated-bert.github.io/siralim-planner
2. Click "Randomize" and confirm the prompt
3. Click "Reset" and confirm the prompt
   * At this point, the path is incorrect
4. Do any other action that modifies the path

### Expected vs. actual results:

Expected: After clicking "Reset" and confirming the prompt, I'm left on https://berated-bert.github.io/siralim-planner/
Actual: After clicking "Reset" and confirming the prompt, I'm left on https://berated-bert.github.io/

**Comment by berated-bert** [comment]
Thank you for letting me know. I have just fixed this in 42148e2.

**Comment by berated-bert** [comment]
Thank you for letting me know. I have just fixed this in 42148e2.
