### ISSUE TITLE
Upload Party: Error not cleared and text not cleared when reopening box

### ISSUE THREAD

**Issue by gurgalex** [berated-bert/siralim-planner#2]
Paste invalid text
Click upload
Error text appears
Close upload party
Reopen upload party
Replace with valid party export.
Without submitting, it would appear now that the valid text has no party traits present.

![image](https://user-images.githubusercontent.com/28968644/134767256-18e8a069-bef5-453d-aec8-b427a4cfbc41.png)

**Comment by berated-bert** [comment]
Thanks, fixed in eb6e8e5. Box now clears the error message when the text is changed.
