### ISSUE TITLE
Upload Party: Upload button impossible to get to when zoomed in

### ISSUE THREAD

**Issue by gurgalex** [berated-bert/siralim-planner#3]
~150% zoom hides the upload button completely. Attempting to scroll the page scrolls the content behind the upload party UI.
![image](https://user-images.githubusercontent.com/28968644/134767331-b9816213-f8b9-44cd-9e22-24330563749a.png)

**Comment by berated-bert** [comment]
Thanks, fixed in eb6e8e5. Box now scales based on screen height, rather than a fixed height.
